/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class Curr_Convert extends javax.swing.JFrame {
    double US=218.60;
    double UK=244.5;
    double Afghan=2.55;
    double Bangladeshi=2.1433;
    double Canadian_Dollar=157.88;
    double Chinese_Yuan=30.38;
    double Egyptian_Pound=9.77;
    double HongKong_Dollar=19.90;
    double Indian_Rupee=2.65;
    double Saudi_Riyal=57.99;
    double Turkish_Lira=11.73;
    
    /**
     * Creates new form Curr_Convert
     */
    
    public Curr_Convert() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        fromCountry = new javax.swing.JComboBox();
        jtxtconvert = new javax.swing.JTextField();
        jLabConvert = new javax.swing.JLabel();
        convert = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(147, 213, 255));

        logo.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        logo.setForeground(new java.awt.Color(81, 96, 255));
        logo.setText("Currency Converter");

        fromCountry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose One..", "United States", "United Kingdom", "Afghani", "Bangladeshi", "Canadian Dollar", "Chinese Yuan", "Saudi Riyal", "Egyptian Pound", "HongKong Dollar", "Indian Rupee", "Turkish Lira" }));
        fromCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromCountryActionPerformed(evt);
            }
        });

        convert.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        convert.setForeground(new java.awt.Color(81, 96, 255));
        convert.setText("CONVERT");
        convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertActionPerformed(evt);
            }
        });

        jLabel1.setText("Choose Country:");

        jLabel2.setText("Enter number:");

        jLabel3.setText("Converted Value:");

        reset.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        reset.setForeground(new java.awt.Color(81, 96, 255));
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jtxtconvert, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fromCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(convert, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabConvert, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fromCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtconvert, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(9, 9, 9)
                .addComponent(jLabConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convert, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon("currency_converter.jpg")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fromCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromCountryActionPerformed

    private void convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertActionPerformed
        // TODO add your handling code here:
        double Pakistani_rupee=Double.parseDouble(jtxtconvert.getText());
        if(fromCountry.getSelectedItem().equals("United States"))
        {
            double convert=Pakistani_rupee*US;
            jLabConvert.setText(""+convert+" PKR");
        }
         if(fromCountry.getSelectedItem().equals("United Kingdom"))
        {
            double convert=Pakistani_rupee*UK;
            jLabConvert.setText(""+convert+" PKR");
        }
          if(fromCountry.getSelectedItem().equals("Afghani"))
        {
            double convert=Pakistani_rupee*Afghan;
            jLabConvert.setText(""+convert+" PKR");
        }
           if(fromCountry.getSelectedItem().equals("Bangladeshi"))
        {
            double convert=Pakistani_rupee*Bangladeshi;
            jLabConvert.setText(""+convert+" PKR");
        }
            if(fromCountry.getSelectedItem().equals("Canadian Dollar"))
        {
            double convert=Pakistani_rupee*Canadian_Dollar;
            jLabConvert.setText(""+convert+" PKR");
        }
             if(fromCountry.getSelectedItem().equals("Chinese Yuan"))
        {
            double convert=Pakistani_rupee*Chinese_Yuan;
            jLabConvert.setText(""+convert+" PKR");
        }
              if(fromCountry.getSelectedItem().equals("Saudi Riyal"))
        {
            double convert=Pakistani_rupee*Saudi_Riyal;
            jLabConvert.setText(""+convert+" PKR");
        }
              if(fromCountry.getSelectedItem().equals("Egptian Pound"))
        {
            double convert=Pakistani_rupee*Egyptian_Pound;
            jLabConvert.setText(""+convert+" PKR");
        }
               if(fromCountry.getSelectedItem().equals("HongKong Dollar"))
        {
            double convert=Pakistani_rupee*HongKong_Dollar;
            jLabConvert.setText(""+convert+" PKR");
        }
                if(fromCountry.getSelectedItem().equals("Indian Rupee"))
        {
            double convert=Pakistani_rupee*Indian_Rupee;
            jLabConvert.setText(""+convert+" PKR");
        }
                 if(fromCountry.getSelectedItem().equals("Turkish Lira"))
        {
            double convert=Pakistani_rupee*Turkish_Lira;
            jLabConvert.setText(""+convert+" PKR");
        }
    }//GEN-LAST:event_convertActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code
            jtxtconvert.setText(null);
            jLabConvert.setText(null);
            fromCountry.setSelectedIndex(0);
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convert;
    private javax.swing.JComboBox fromCountry;
    private javax.swing.JLabel jLabConvert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jtxtconvert;
    private javax.swing.JLabel logo;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
